### ISSUE TITLE
Throws error when used under Python3.13.x

### ISSUE THREAD

**Issue by cloudcodger** [proxmoxer/proxmoxer#198]
I have an Ansible playbook that use a Role that uses modules based off the `community.general` `proxmox` module, except that they use the `openssh` backend. This works fine with Python 3.12.x but now fails with Python 3.13.x with the error `Chosen backend requires 'openssh_wrapper' module`.

This message is coming from `proxmoxer` when it checks to see if the `openssh_wrapper` module is installed and for some reason it fails even when the module is there.

Example of the playbook running:

```
(venv129) cloudcodger/showcase % python3 --version
Python 3.12.9
(venv129) cloudcodger/showcase % ansible-playbook test_pve.yml

PLAY [Configure the Proxmox Datacenter.] ***************************************************************************************************

TASK [Test calling openssh module.] ********************************************************************************************************
ok: [localhost]

PLAY RECAP *********************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

Example of the playbook run with the error:

```
(venv132) cloudcodger/showcase % python3 --version
Python 3.13.2
(venv132) cloudcodger/showcase % ansible-playbook test_pve.yml

PLAY [Configure the Proxmox Datacenter.] ***************************************************************************************************

TASK [Test calling openssh module.] ********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Chosen backend requires 'openssh_wrapper' module\n\n", "module_stdout": "", "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *********************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
In both cases, using `proxmoxer` module version `2.2.0`.

Here is the `test_pve.yml` playbook that is failing with Python 3.13.

```
---
- name: Configure the Proxmox Datacenter.
  gather_facts: false
  hosts: localhost

  tasks:
    - name: Test calling openssh module.
      cloudcodger.proxmox_openssh.proxmox_group:
        api_host: gadget1
        api_user: root
        api_port: 22
        api_sudo: false
        group: Admin
        state: present
```

**Comment by jhollowe** [comment]
I was working on trying to get py3.13 working, but it looks like 3.13 deprecated something that the openssh-wrapper library was using. Since that library hasn't been updated in many years and has not accepted previous PRs, I just forked it and added a fix for this issue.

Feel free to use `git+https://github.com/proxmoxer/openssh-wrapper.git@master` in your requirements.txt (or however else you are installing python libraries). I need to reach out to the current maintainers of `openssh-wrapper` and see if they want to continue owning it or would like this org to take it over.

**Comment by cloudcodger** [comment]
I have been able to work around this issue by running the following command.

```
sed -i 's/import pipes/import shlex/; s/pipes.quote/shlex.quote/' ~/.venv/lib/python3.*/site-packages/openssh_wrapper.py
```

However, this leads to the next issue that produces the error.

```
[ERROR]: Task failed: Module failed: ProxmoxAnsible.get_storages() got an unexpected keyword argument 'type'
```

It looks like some kind of validation has changed. According to my searching:

> Python 3.13 introduced stricter internal handling of function signatures and keyword-only arguments. If the proxmoxer 2.3.0 library defines get_storages() with a signature that Python 3.13 interprets differently (e.g., expecting positional-only arguments or having a signature mismatch due to how *args/**kwargs are passed internally), the call fails with unexpected keyword argument 'type'.

This becomes a blocker on Debian 13 (Trixie), where Python 3.13 is the version installed by the OS.

Not sure if this should be a new bug report or simply part of this one where they both are related to Python 3.13.x.

Edit:
I should mention that the is after having moved to the new `community.proxmox` collection now that Ansible no longer includes the Proxmox modules in `community.general`.

**Comment by dlucredativ** [comment]
proxmoxer doesn't call `ProxmoxAnsible.get_storages()`, and the error is not Python 3.13 related. https://github.com/ansible-collections/community.proxmox/commit/2827e483d3ba0e8b97592a530846bf63264ca8cd renamed the parameter.

**Comment by cloudcodger** [comment]
Thank you @dlucredativ for that information. I should have researched it further. Because of the search results saying what it did, I made a bad assumption.
